name: Main

on:
  schedule:
    - cron: '0 0 * * 0' 
  push:
    branches:
      - master
  workflow_dispatch:

  
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.1'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r u installResources.ps1
        
    - name: Build executable
      run: pyinstaller.exe --onefile --noconsole main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-exe
        path: dist/main.exe
